packages:
  - '.'

allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@astrojs/cloudflare@14.2.5'
  - '@cloudflare/workers-types@5.20260826.1'
  - astro@7.2.7
  - miniflare@5.20260825.0-alpha
  - wrangler@4.126.0
